config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  
  post "/users(.:format)" => 'users#create', as: "users" do
    resource :password,
    controller: "clearance/passwords",
    only: [:create, :edit, :update]
  end
  
  post "/session(.:format)" => 'sessions#create', as: "session"
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  
  resources :sales
  resources :attractions
  resources :employees
  resources :companies
  root 'attractions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  before_action :require_login
  before_action :set_attraction, only: [:show, :edit, :update, :destroy]

  # GET /attractions
  # GET /attractions.json
  def index
    @company = get_my_company_id

    @attractions = Attraction.where(company_id:@company.id)
  end

  # GET /attractions/1
  # GET /attractions/1.json
  def show
  end

  # GET /attractions/new
  def new
    @attraction = Attraction.new
  end

  # GET /attractions/1/edit
  def edit
  end

  # POST /attractions
  # POST /attractions.json
  def create
    if am_i_employee?
      return
    end
    
    @company = get_my_company_id
    @attraction = Attraction.new
    @attraction.name = attraction_params[:name]
    @attraction.address = attraction_params[:address]
    @attraction.duration_minutes = attraction_params[:duration_minutes]
    @attraction.max_capacity = attraction_params[:max_capacity]
    @attraction.picture = attraction_params[:picture]
    @attraction.company_id = @company.id

    respond_to do |format|
      if @attraction.save
        format.html { redirect_to @attraction, notice: 'Attraction was successfully created.' }
        format.json { render :show, status: :created, location: @attraction }
      else
        format.html { render :new }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attractions/1
  # PATCH/PUT /attractions/1.json
  def update
    respond_to do |format|
      if @attraction.update(attraction_params)
        format.html { redirect_to @attraction, notice: 'Attraction was successfully updated.' }
        format.json { render :show, status: :ok, location: @attraction }
      else
        format.html { render :edit }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attractions/1
  # DELETE /attractions/1.json
  def destroy
    if am_i_employee?
      return
    end
    @attraction.destroy
    respond_to do |format|
      format.html { redirect_to attractions_url, notice: 'Attraction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attraction
      @attraction = Attraction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attraction_params
      params.require(:attraction).permit(:name, :address, :duration_minutes, :max_capacity, :company_id, :picture)
    end

    def get_my_company_id
      @employee = Employee.find_by(user_id:current_user.id)
    
      if @employee
        @company = Company.find(id=@employee.company_id)
      else
        @company = Company.find_by(user_id:current_user.id)
      end
    end

    def am_i_employee?
      @employee = Employee.find_by(user_id:current_user.id)
      if @employee
        return true
      else
        return false
      end
    end
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/views/attractions/_form.html.erb
<%= form_with(model: attraction, local: true) do |form| %>
  <% if attraction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attraction.errors.count, "error") %> prohibited this attraction from being saved:</h2>

      <ul>
      <% attraction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :duration_minutes %>
    <%= form.number_field :duration_minutes %>
  </div>

  <div class="field">
    <%= form.label :max_capacity %>
    <%= form.number_field :max_capacity %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attractions/edit.html.erb
<h1>Editing Attraction</h1>

<%= render 'form', attraction: @attraction %>

<%= link_to 'Show', @attraction %> |
<%= link_to 'Back', attractions_path %>

app/views/attractions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attractions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Duration minutes</th>
      <th>Max capacity</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @attractions %>
      <% @attractions.each do |attraction| %>
        <tr>
          <td><%= attraction.name %></td>
          <td><%= attraction.address %></td>
          <td><%= attraction.duration_minutes %></td>
          <td><%= attraction.max_capacity %></td>
          <td><%= attraction.company %></td>
          <td><%= link_to 'Show', attraction %></td>
          <td><%= link_to 'Edit', edit_attraction_path(attraction) %></td>
          <td><%= link_to 'Destroy', attraction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attraction', new_attraction_path %>

app/views/attractions/new.html.erb
<h1>New Attraction</h1>

<%= render 'form', attraction: @attraction %>

<%= link_to 'Back', attractions_path %>

app/views/attractions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @attraction.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @attraction.address %>
</p>

<p>
  <strong>Duration minutes:</strong>
  <%= @attraction.duration_minutes %>
</p>

<p>
  <strong>Max capacity:</strong>
  <%= @attraction.max_capacity %>
</p>

<p>
  <strong>Company:</strong>
  <%= @attraction.company %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@attraction.picture) %>
</p>

<%= link_to 'Edit', edit_attraction_path(@attraction) %> |
<%= link_to 'Back', attractions_path %>